name: Configure pyenv and pick the right version
on: push

jobs:
 # python installtion
  install-python:
  # should run on linux based operating system
    runs-on: ubuntu-latest
  
     steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
